import {
  GlobalOutlined,
  DashboardOutlined,
  CloudOutlined,
  DeploymentUnitOutlined,
  ClusterOutlined,
  CloudServerOutlined,
  SearchOutlined,
  ReloadOutlined,
  BulbTwoTone,
  RestOutlined,
} from '@ant-design/icons'
import {
  IconAnquanzu,
  IconShouyeshouye,
  IconYunjisuan,
  IconYuncunchu,
  IconYunjiankong,
  IconComponent,
  IconWangluo,
  IconHost,
  IconCluster,
  IconDatacenter,
  IconClusterMonitor,
  IconHostrMonitor,
  IconIprMonitor,
  IconStoragerMonitor,
  IconVlanMonitor,
  IconVmMonitor,
} from '@components/iconfont'
import {
  ClusterSvg,
  DataCenterSvg,
  HostCloseSvg,
  HostPauseSvg,
  HostRuningSvg,
  HostUnkownSvg,
  HostMaintenanceSvg,
  VmCloseSvg,
  VmPauseSvg,
  VmRunningSvg,
  VmUnkownSvg,
} from '@components/svgIcon'

const _hostSvg = {
  close: HostCloseSvg,
  pause: HostPauseSvg,
  running: HostRuningSvg,
  unkown: HostUnkownSvg,
  maintenance: HostMaintenanceSvg,
}

const _vmSvg = {
  close: VmCloseSvg,
  pause: VmPauseSvg,
  running: VmRunningSvg,
  unkown: VmUnkownSvg,
}

export {
  GlobalOutlined,
  DashboardOutlined,
  CloudOutlined,
  DeploymentUnitOutlined,
  ClusterOutlined,
  CloudServerOutlined,
  SearchOutlined,
  ReloadOutlined,
  BulbTwoTone,
  RestOutlined,
  IconAnquanzu,
  IconShouyeshouye,
  IconYunjisuan,
  IconYuncunchu,
  IconYunjiankong,
  IconComponent,
  IconWangluo,
  IconHost,
  IconCluster,
  IconDatacenter,
  IconClusterMonitor,
  IconHostrMonitor,
  IconIprMonitor,
  IconStoragerMonitor,
  IconVlanMonitor,
  IconVmMonitor,
  ClusterSvg,
  DataCenterSvg,
  _hostSvg,
  _vmSvg,
}
